# Generated by Django 3.1.4 on 2020-12-17 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lambai_pent', models.CharField(max_length=10, null=True)),
                ('kamar_pent', models.CharField(max_length=10, null=True)),
                ('seet_pent', models.CharField(max_length=10, null=True)),
                ('mori_pent', models.CharField(max_length=10, null=True)),
                ('jangh_pent', models.CharField(max_length=10, null=True)),
                ('jolo_pent', models.CharField(max_length=10, null=True)),
                ('gothan_pent', models.CharField(max_length=10, null=True)),
                ('lees_pent', models.CharField(max_length=10, null=True)),
                ('vigat_pent', models.CharField(max_length=200, null=True)),
                ('lambai_shirt', models.CharField(max_length=10, null=True)),
                ('chati_shirt', models.CharField(max_length=10, null=True)),
                ('bay_shirt', models.CharField(max_length=10, null=True)),
                ('solder_shirt', models.CharField(max_length=10, null=True)),
                ('kamar_shirt', models.CharField(max_length=10, null=True)),
                ('pech_shirt', models.CharField(max_length=10, null=True)),
                ('kolar_shirt', models.CharField(max_length=10, null=True)),
                ('kaf_shirt', models.CharField(max_length=10, null=True)),
                ('vigat_shirt', models.CharField(max_length=200, null=True)),
                ('photo', models.ImageField(null=True, upload_to='photo')),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('status', models.CharField(default='pending', max_length=10)),
                ('order_CustomerId',
                 models.ForeignKey(db_column='order_CustomerId', on_delete=django.db.models.deletion.CASCADE,
                                   to='customer.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lambai_pent', models.CharField(max_length=10, null=True)),
                ('kamar_pent', models.CharField(max_length=10, null=True)),
                ('seet_pent', models.CharField(max_length=10, null=True)),
                ('mori_pent', models.CharField(max_length=10, null=True)),
                ('jangh_pent', models.CharField(max_length=10, null=True)),
                ('jolo_pent', models.CharField(max_length=10, null=True)),
                ('gothan_pent', models.CharField(max_length=10, null=True)),
                ('lees_pent', models.CharField(max_length=10, null=True)),
                ('lambai_shirt', models.CharField(max_length=10, null=True)),
                ('chati_shirt', models.CharField(max_length=10, null=True)),
                ('bay_shirt', models.CharField(max_length=10, null=True)),
                ('solder_shirt', models.CharField(max_length=10, null=True)),
                ('kamar_shirt', models.CharField(max_length=10, null=True)),
                ('pech_shirt', models.CharField(max_length=10, null=True)),
                ('kolar_shirt', models.CharField(max_length=10, null=True)),
                ('kaf_shirt', models.CharField(max_length=10, null=True)),
                ('measurement_CustomerId',
                 models.ForeignKey(db_column='measurement_CustomerId', on_delete=django.db.models.deletion.CASCADE,
                                   to='customer.customer')),
            ],
        ),
    ]
